
module "platinium" {
  source  = "terraform-aws-modules/eks/aws//examples/launch_templates"
  version = "11.0.0"
  region = var.region
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.platinium.cluster_endpoint
}

output "kube_config" {
  description = "kubectl config as generated by the module."
  value       = module.platinium.kubectl_config
}

variable region {}
